export default {
  REQUEST_SEARCH_RESULTS: 'REQUEST_SEARCH_RESULTS',
  RECEIVE_SEARCH_RESULTS: 'RECEIVE_SEARCH_RESULTS',
  SET_QUERY: 'SET_QUERY',
  SET_ACTIVE_SEARCH_TYPE: 'SET_ACTIVE_SEARCH_TYPE',
  TOGGLE_DISPLAY_SEARCH_TYPES: 'TOGGLE_DISPLAY_SEARCH_TYPES',
  INCREMENT_PAGE: 'INCREMENT_PAGE',
  DECREMENT_PAGE: 'DECREMENT_PAGE',
  RESET_PAGE_COUNT: 'RESET_PAGE_COUNT'
}
